services:
  ai_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_api
    image: ai-myapi:latest
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8123:8123"
